# Generated by Django 2.2.5 on 2019-10-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_auto_20191012_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='ecom.Product'),
        ),
    ]
