# Generated by Django 2.2.5 on 2019-10-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_auto_20191006_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cheapest',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='size',
            name='price',
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.Product'),
        ),
        migrations.AlterField(
            model_name='size',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.Product'),
        ),
    ]
