# Generated by Django 2.2.5 on 2019-10-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postalcode',
            new_name='Postalcode',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Billing',
            new_name='billing',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Address'),
        ),
    ]
